name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./
          branch: gh-pages